# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import piper_pb2 as piper__pb2


class PiperCommsServiceStub(object):
    """Master communication interface hosted by the jetson_nx_mind server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstablishVoiceSession = channel.stream_stream(
                '/piper.PiperCommsService/EstablishVoiceSession',
                request_serializer=piper__pb2.AudioFrame.SerializeToString,
                response_deserializer=piper__pb2.AudioFrame.FromString,
                )
        self.SignalStateChange = channel.unary_unary(
                '/piper.PiperCommsService/SignalStateChange',
                request_serializer=piper__pb2.StatePacket.SerializeToString,
                response_deserializer=piper__pb2.StateResponse.FromString,
                )


class PiperCommsServiceServicer(object):
    """Master communication interface hosted by the jetson_nx_mind server
    """

    def EstablishVoiceSession(self, request_iterator, context):
        """Bidirectional audio session. The Pi streams microphone data up, 
        while the Jetson streams synthesized TTS audio back down simultaneously.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalStateChange(self, request, context):
        """Unary channel used by the Pi to instantly signal hardware events (like a wake word)
        or by the Jetson to toggle hardware states (like turning on/off the display)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PiperCommsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstablishVoiceSession': grpc.stream_stream_rpc_method_handler(
                    servicer.EstablishVoiceSession,
                    request_deserializer=piper__pb2.AudioFrame.FromString,
                    response_serializer=piper__pb2.AudioFrame.SerializeToString,
            ),
            'SignalStateChange': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalStateChange,
                    request_deserializer=piper__pb2.StatePacket.FromString,
                    response_serializer=piper__pb2.StateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'piper.PiperCommsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PiperCommsService(object):
    """Master communication interface hosted by the jetson_nx_mind server
    """

    @staticmethod
    def EstablishVoiceSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/piper.PiperCommsService/EstablishVoiceSession',
            piper__pb2.AudioFrame.SerializeToString,
            piper__pb2.AudioFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignalStateChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/piper.PiperCommsService/SignalStateChange',
            piper__pb2.StatePacket.SerializeToString,
            piper__pb2.StateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
