# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: piper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpiper.proto\x12\x05piper\"Z\n\nAudioFrame\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08\x63hunk_id\x18\x04 \x01(\x03\"E\n\x0bStatePacket\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"2\n\rStateResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x95\x01\n\x11PiperCommsService\x12\x41\n\x15\x45stablishVoiceSession\x12\x11.piper.AudioFrame\x1a\x11.piper.AudioFrame(\x01\x30\x01\x12=\n\x11SignalStateChange\x12\x12.piper.StatePacket\x1a\x14.piper.StateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'piper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOFRAME']._serialized_start=22
  _globals['_AUDIOFRAME']._serialized_end=112
  _globals['_STATEPACKET']._serialized_start=114
  _globals['_STATEPACKET']._serialized_end=183
  _globals['_STATERESPONSE']._serialized_start=185
  _globals['_STATERESPONSE']._serialized_end=235
  _globals['_PIPERCOMMSSERVICE']._serialized_start=238
  _globals['_PIPERCOMMSSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
