# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spatial_matrix.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'spatial_matrix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14spatial_matrix.proto\x12\x05piper\"D\n\x13VisionStreamRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1a\n\x12request_compressed\x18\x02 \x01(\x08\"\x88\x01\n\x0bVisionFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x13\n\x0b\x66rame_bytes\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63urrent_pan\x18\x03 \x01(\x02\x12\x14\n\x0c\x63urrent_tilt\x18\x04 \x01(\x02\x12\x11\n\tactive_id\x18\x05 \x01(\t\x12\x13\n\x0bis_thinking\x18\x06 \x01(\x08\x32W\n\rSpatialMatrix\x12\x46\n\x12StreamVisionMatrix\x12\x1a.piper.VisionStreamRequest\x1a\x12.piper.VisionFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spatial_matrix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VISIONSTREAMREQUEST']._serialized_start=31
  _globals['_VISIONSTREAMREQUEST']._serialized_end=99
  _globals['_VISIONFRAME']._serialized_start=102
  _globals['_VISIONFRAME']._serialized_end=238
  _globals['_SPATIALMATRIX']._serialized_start=240
  _globals['_SPATIALMATRIX']._serialized_end=327
# @@protoc_insertion_point(module_scope)
